package mybatis_generator.dao;

import java.util.List;
import mybatis_generator.pojo.Emp2;
import mybatis_generator.pojo.Emp2Example;
import org.apache.ibatis.annotations.Param;

public interface Emp2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    long countByExample(Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    int deleteByExample(Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Short EMPNO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    int insert(Emp2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    int insertSelective(Emp2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    List<Emp2> selectByExample(Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    Emp2 selectByPrimaryKey(Short EMPNO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Emp2 record, @Param("example") Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Emp2 record, @Param("example") Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Emp2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    int updateByPrimaryKey(Emp2 record);
}