package mybatis_generator.pojo;

import java.io.Serializable;

public class Dept2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.DEPT2.DEPTNO
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private Short DEPTNO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.DEPT2.DNAME
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private String DNAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.DEPT2.LOC
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private String LOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DA104.DEPT2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.DEPT2.DEPTNO
     *
     * @return the value of DA104.DEPT2.DEPTNO
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public Short getDEPTNO() {
        return DEPTNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.DEPT2.DEPTNO
     *
     * @param DEPTNO the value for DA104.DEPT2.DEPTNO
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setDEPTNO(Short DEPTNO) {
        this.DEPTNO = DEPTNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.DEPT2.DNAME
     *
     * @return the value of DA104.DEPT2.DNAME
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public String getDNAME() {
        return DNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.DEPT2.DNAME
     *
     * @param DNAME the value for DA104.DEPT2.DNAME
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setDNAME(String DNAME) {
        this.DNAME = DNAME == null ? null : DNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.DEPT2.LOC
     *
     * @return the value of DA104.DEPT2.LOC
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public String getLOC() {
        return LOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.DEPT2.LOC
     *
     * @param LOC the value for DA104.DEPT2.LOC
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setLOC(String LOC) {
        this.LOC = LOC == null ? null : LOC.trim();
    }
}