package mybatis_generator.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Emp2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.EMP2.EMPNO
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private Short EMPNO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.EMP2.ENAME
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private String ENAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.EMP2.JOB
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private String JOB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.EMP2.HIREDATE
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private Date HIREDATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.EMP2.SAL
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private BigDecimal SAL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.EMP2.COMM
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private BigDecimal COMM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DA104.EMP2.DEPTNO
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private Short DEPTNO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DA104.EMP2
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.EMP2.EMPNO
     *
     * @return the value of DA104.EMP2.EMPNO
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public Short getEMPNO() {
        return EMPNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.EMP2.EMPNO
     *
     * @param EMPNO the value for DA104.EMP2.EMPNO
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setEMPNO(Short EMPNO) {
        this.EMPNO = EMPNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.EMP2.ENAME
     *
     * @return the value of DA104.EMP2.ENAME
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public String getENAME() {
        return ENAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.EMP2.ENAME
     *
     * @param ENAME the value for DA104.EMP2.ENAME
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setENAME(String ENAME) {
        this.ENAME = ENAME == null ? null : ENAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.EMP2.JOB
     *
     * @return the value of DA104.EMP2.JOB
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public String getJOB() {
        return JOB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.EMP2.JOB
     *
     * @param JOB the value for DA104.EMP2.JOB
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setJOB(String JOB) {
        this.JOB = JOB == null ? null : JOB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.EMP2.HIREDATE
     *
     * @return the value of DA104.EMP2.HIREDATE
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public Date getHIREDATE() {
        return HIREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.EMP2.HIREDATE
     *
     * @param HIREDATE the value for DA104.EMP2.HIREDATE
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setHIREDATE(Date HIREDATE) {
        this.HIREDATE = HIREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.EMP2.SAL
     *
     * @return the value of DA104.EMP2.SAL
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public BigDecimal getSAL() {
        return SAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.EMP2.SAL
     *
     * @param SAL the value for DA104.EMP2.SAL
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setSAL(BigDecimal SAL) {
        this.SAL = SAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.EMP2.COMM
     *
     * @return the value of DA104.EMP2.COMM
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public BigDecimal getCOMM() {
        return COMM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.EMP2.COMM
     *
     * @param COMM the value for DA104.EMP2.COMM
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setCOMM(BigDecimal COMM) {
        this.COMM = COMM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DA104.EMP2.DEPTNO
     *
     * @return the value of DA104.EMP2.DEPTNO
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public Short getDEPTNO() {
        return DEPTNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DA104.EMP2.DEPTNO
     *
     * @param DEPTNO the value for DA104.EMP2.DEPTNO
     *
     * @mbg.generated Sun Jul 05 19:22:58 GMT+08:00 2020
     */
    public void setDEPTNO(Short DEPTNO) {
        this.DEPTNO = DEPTNO;
    }
}